/* ===== Jazykový balíček: NĚMČINA (de) =====
   Obsah pro úroveň A1 (další úrovně se budou přidávat sem).
   Chceš-li upravit slovíčka nebo gramatiku němčiny, edituj TENTO soubor. */
(function(){
/* ===== NĚMČINA A1: SLOVÍČKA ===== */
const CATS_A1_DE=[
 {id:"de_greet",title:"Pozdravy a základní fráze",vocab:[["Hallo","ahoj"],["Guten Tag","dobrý den"],["Auf Wiedersehen","na shledanou"],["Bitte","prosím"],["Danke","děkuji"],["Ja","ano"],["Nein","ne"],["Entschuldigung","promiňte"],["Wie geht's?","jak se máš?"],["Tschüss","čau"]],sentences:[["___ , wie geht es dir?","Hallo","Ahoj, jak se máš?"],["Ich sage ___ , wenn ich gehe.","Tschüss","Říkám čau, když odcházím."],["___ ! Können Sie mir helfen?","Entschuldigung","Promiňte! Můžete mi pomoct?"],["___ für deine Hilfe.","Danke","Děkuji za tvou pomoc."],["___ , mein Name ist Anna.","Guten Tag","Dobrý den, jmenuji se Anna."]]},
 {id:"de_numbers",title:"Čísla",vocab:[["eins","jedna"],["zwei","dva"],["drei","tři"],["vier","čtyři"],["fünf","pět"],["sechs","šest"],["sieben","sedm"],["acht","osm"],["neun","devět"],["zehn","deset"]],sentences:[["Ich habe ___ Brüder.","zwei","Mám dva bratry."],["Das Kind ist ___ Jahre alt.","fünf","Dítě je pět let staré."],["Wir brauchen ___ Äpfel.","zehn","Potřebujeme deset jablek."],["Er hat ___ Katzen.","drei","Má tři kočky."],["Sie zählt bis ___ .","sieben","Počítá do sedmi."]]},
 {id:"de_family",title:"Rodina",vocab:[["die Mutter","matka"],["der Vater","otec"],["die Schwester","sestra"],["der Bruder","bratr"],["die Eltern","rodiče"],["das Kind","dítě"],["die Großmutter","babička"],["der Großvater","dědeček"],["die Tante","teta"],["der Onkel","strýc"]],sentences:[["Meine ___ heißt Maria.","Mutter","Moje matka se jmenuje Maria."],["Mein ___ arbeitet viel.","Vater","Můj otec hodně pracuje."],["Ich habe eine ___ .","Schwester","Mám sestru."],["Meine ___ wohnen in Berlin.","Eltern","Moji rodiče bydlí v Berlíně."],["Das ___ spielt im Garten.","Kind","Dítě si hraje na zahradě."]]},
 {id:"de_food",title:"Jídlo a pití",vocab:[["das Brot","chléb"],["das Wasser","voda"],["der Kaffee","káva"],["die Milch","mléko"],["der Apfel","jablko"],["das Fleisch","maso"],["der Käse","sýr"],["das Ei","vejce"],["der Reis","rýže"],["der Zucker","cukr"]],sentences:[["Ich trinke gern ___ .","Kaffee","Rád piji kávu."],["Wir kaufen ___ und Milch.","Brot","Kupujeme chléb a mléko."],["Sie isst einen ___ .","Apfel","Jí jablko."],["Er möchte kein ___ essen.","Fleisch","Nechce jíst maso."],["Bitte gib mir etwas ___ .","Wasser","Prosím, dej mi trochu vody."]]},
 {id:"de_colors",title:"Barvy",vocab:[["rot","červená"],["blau","modrá"],["grün","zelená"],["gelb","žlutá"],["schwarz","černá"],["weiß","bílá"],["braun","hnědá"],["orange","oranžová"],["grau","šedá"],["lila","fialová"]],sentences:[["Der Himmel ist ___ .","blau","Obloha je modrá."],["Ihr Auto ist ___ .","rot","Její auto je červené."],["Die Blätter werden im Herbst ___ .","gelb","Listy na podzim žloutnou."],["Sein Hemd ist ___ .","schwarz","Jeho košile je černá."],["Die Katze ist ___ und weiß.","braun","Kočka je hnědá a bílá."]]},
 {id:"de_animals",title:"Zvířata",vocab:[["der Hund","pes"],["die Katze","kočka"],["der Vogel","pták"],["das Pferd","kůň"],["die Kuh","kráva"],["der Fisch","ryba"],["die Maus","myš"],["der Löwe","lev"],["der Bär","medvěd"],["das Schaf","ovce"]],sentences:[["Der ___ bellt laut.","Hund","Pes hlasitě štěká."],["Die ___ schläft auf dem Sofa.","Katze","Kočka spí na gauči."],["Ein ___ singt im Baum.","Vogel","Pták zpívá na stromě."],["Das ___ läuft schnell.","Pferd","Kůň běží rychle."],["Die ___ gibt Milch.","Kuh","Kráva dává mléko."]]},
 {id:"de_house",title:"Dům a byt",vocab:[["das Haus","dům"],["die Wohnung","byt"],["das Zimmer","pokoj"],["die Küche","kuchyně"],["das Bad","koupelna"],["das Fenster","okno"],["die Tür","dveře"],["der Tisch","stůl"],["der Stuhl","židle"],["das Bett","postel"]],sentences:[["Wir wohnen in einem großen ___ .","Haus","Bydlíme ve velkém domě."],["Die ___ ist sehr klein.","Küche","Kuchyně je velmi malá."],["Er öffnet das ___ .","Fenster","Otevírá okno."],["Das Bett steht in meinem ___ .","Zimmer","Postel je v mém pokoji."],["Sie setzt sich auf den ___ .","Stuhl","Sedá si na židli."]]},
 {id:"de_time",title:"Čas a dny",vocab:[["heute","dnes"],["morgen","zítra"],["gestern","včera"],["die Woche","týden"],["der Tag","den"],["die Stunde","hodina"],["die Minute","minuta"],["der Montag","pondělí"],["das Wochenende","víkend"],["jetzt","teď"]],sentences:[["___ ist Montag.","Heute","Dnes je pondělí."],["Wir treffen uns ___ .","morgen","Setkáme se zítra."],["Ich habe ___ keine Zeit.","jetzt","Teď nemám čas."],["Das Meeting dauert eine ___ .","Stunde","Schůzka trvá hodinu."],["Am ___ gehen wir spazieren.","Wochenende","O víkendu chodíme na procházku."]]},
 {id:"de_body",title:"Tělo",vocab:[["der Kopf","hlava"],["das Auge","oko"],["die Nase","nos"],["der Mund","ústa"],["das Ohr","ucho"],["die Hand","ruka"],["der Fuß","noha/chodidlo"],["der Arm","paže"],["der Bauch","břicho"],["das Haar","vlasy"]],sentences:[["Mein ___ tut weh.","Kopf","Bolí mě hlava."],["Er hat ein blaues ___ .","Auge","Má modré oko."],["Die ___ ist klein.","Nase","Nos je malý."],["Meine ___ ist kalt.","Hand","Moje ruka je studená."],["Sein ___ ist lang.","Arm","Jeho paže je dlouhá."]]},
 {id:"de_clothes",title:"Oblečení",vocab:[["die Hose","kalhoty"],["das Hemd","košile"],["der Rock","sukně"],["die Jacke","bunda"],["die Schuhe","boty"],["das T-Shirt","tričko"],["der Pullover","svetr"],["die Mütze","čepice"],["der Mantel","kabát"],["die Socke","ponožka"]],sentences:[["Ich trage eine neue ___ .","Hose","Nosím nové kalhoty."],["Sein ___ ist blau.","Hemd","Jeho košile je modrá."],["Sie kauft einen warmen ___ .","Mantel","Kupuje si teplý kabát."],["Im Winter trage ich einen ___ .","Pullover","V zimě nosím svetr."],["Meine ___ sind neu.","Schuhe","Moje boty jsou nové."]]},
 {id:"de_town",title:"Město",vocab:[["die Stadt","město"],["die Straße","ulice"],["der Markt","trh"],["das Geschäft","obchod"],["die Schule","škola"],["das Krankenhaus","nemocnice"],["die Kirche","kostel"],["der Park","park"],["das Rathaus","radnice"],["die Brücke","most"]],sentences:[["Wir wohnen in einer großen ___ .","Stadt","Bydlíme ve velkém městě."],["Das ___ ist heute geschlossen.","Geschäft","Ten obchod je dnes zavřený."],["Die Kinder gehen zur ___ .","Schule","Děti jdou do školy."],["Der ___ ist sehr schön im Frühling.","Park","Park je na jaře moc hezký."],["Wir treffen uns auf dem ___ .","Markt","Setkáme se na trhu."]]},
 {id:"de_transport",title:"Doprava",vocab:[["das Auto","auto"],["der Bus","autobus"],["der Zug","vlak"],["das Fahrrad","kolo"],["das Flugzeug","letadlo"],["die U-Bahn","metro"],["das Taxi","taxi"],["der Bahnhof","nádraží"],["das Ticket","jízdenka"],["die Straßenbahn","tramvaj"]],sentences:[["Ich fahre mit dem ___ zur Arbeit.","Auto","Jezdím do práce autem."],["Der ___ kommt um acht Uhr.","Zug","Vlak přijíždí v osm hodin."],["Sie fährt gern mit dem ___ .","Fahrrad","Ráda jezdí na kole."],["Wir nehmen die ___ zum Flughafen.","U-Bahn","Jedeme metrem na letiště."],["Ich kaufe ein ___ für den Bus.","Ticket","Kupuji jízdenku na autobus."]]},
 {id:"de_weather",title:"Počasí",vocab:[["die Sonne","slunce"],["der Regen","déšť"],["der Schnee","sníh"],["der Wind","vítr"],["die Wolke","mrak"],["das Gewitter","bouřka"],["warm","teplo"],["kalt","zima/chladno"],["die Temperatur","teplota"],["der Himmel","obloha"]],sentences:[["Heute scheint die ___ .","Sonne","Dnes svítí slunce."],["Im Winter gibt es viel ___ .","Schnee","V zimě je hodně sněhu."],["Der ___ ist heute stark.","Wind","Vítr je dnes silný."],["Es ist sehr ___ draußen.","kalt","Venku je velká zima."],["Morgen kommt ein ___ .","Gewitter","Zítra přijde bouřka."]]},
 {id:"de_verbs",title:"Základní slovesa",vocab:[["gehen","jít"],["kommen","přijít"],["essen","jíst"],["trinken","pít"],["sehen","vidět"],["sprechen","mluvit"],["machen","dělat"],["lesen","číst"],["schreiben","psát"],["schlafen","spát"]],sentences:[["Ich möchte etwas ___ .","essen","Chci něco sníst."],["Er möchte Wasser ___ .","trinken","Chce pít vodu."],["Wir möchten den Film ___ .","sehen","Chceme vidět ten film."],["Kannst du langsamer ___ ?","sprechen","Můžeš mluvit pomaleji?"],["Ich muss jetzt ___ .","schlafen","Teď musím spát."]]},
 {id:"de_adj",title:"Přídavná jména",vocab:[["groß","velký"],["klein","malý"],["neu","nový"],["alt","starý"],["gut","dobrý"],["schlecht","špatný"],["schnell","rychlý"],["langsam","pomalý"],["schön","hezký"],["glücklich","šťastný"]],sentences:[["Das Haus ist sehr ___ .","groß","Ten dům je velmi velký."],["Mein Auto ist nicht ___ , es ist alt.","neu","Moje auto není nové, je staré."],["Die Suppe schmeckt ___ .","gut","Polévka chutná dobře."],["Der Zug ist sehr ___ .","schnell","Vlak je velmi rychlý."],["Sie ist heute sehr ___ .","glücklich","Dnes je velmi šťastná."]]}
];
/* ===== NĚMČINA A1: GRAMATIKA ===== */
const GRAMMAR_A1_DE=[
 {id:"de_g_seinhaben",title:"Sein a haben (být a mít)",type:"grammar",theory:"Slovesa <b>sein</b> (být) a <b>haben</b> (mít) patří mezi nejdůležitější nepravidelná slovesa v němčině. Musí se naučit nazpaměť: ich bin/habe, du bist/hast, er/sie/es ist/hat, wir sind/haben, ihr seid/habt, sie/Sie sind/haben.",table:[["Osoba","sein","haben"],["ich","bin","habe"],["du","bist","hast"],["er/sie/es","ist","hat"],["wir","sind","haben"],["ihr","seid","habt"],["sie/Sie","sind","haben"]],items:[["Ich ___ müde.","bin",["bin","bist","ist"],"Jsem unavený."],["Du ___ sehr nett.","bist",["bist","bin","ist"],"Jsi velmi milý."],["Er ___ ein Lehrer.","ist",["ist","bin","sind"],"Je učitel."],["Wir ___ Studenten.","sind",["sind","ist","seid"],"Jsme studenti."],["Ich ___ einen Hund.","habe",["habe","hast","hat"],"Mám psa."],["Sie ___ zwei Kinder.","hat",["hat","habe","haben"],"Má dvě děti."],["Ihr ___ viel Zeit.","habt",["habt","hat","haben"],"Máte hodně času."],["Sie ___ ein neues Auto.","haben",["haben","hat","habt"],"Mají nové auto."]]},
 {id:"de_g_artikel",title:"Členy der/die/das",type:"grammar",theory:"Němčina má tři rody podstatných jmen: mužský (<b>der</b>), ženský (<b>die</b>) a střední (<b>das</b>). V množném čísle se vždy používá <b>die</b>. Rod se musí učit s každým slovem zvlášť.",table:[["Rod","Člen","Příklad"],["mužský","der","der Mann"],["ženský","die","die Frau"],["střední","das","das Kind"],["množné číslo","die","die Kinder"]],items:[["___ Mann ist groß.","Der",["Der","Die","Das"],"Ten muž je vysoký."],["___ Frau liest ein Buch.","Die",["Die","Der","Das"],"Ta žena čte knihu."],["___ Kind spielt draußen.","Das",["Das","Der","Die"],"To dítě si hraje venku."],["___ Kinder spielen draußen.","Die",["Die","Der","Das"],"Ty děti si hrají venku."],["___ Hund läuft schnell.","Der",["Der","Die","Das"],"Ten pes běží rychle."],["___ Katze schläft.","Die",["Die","Der","Das"],"Ta kočka spí."],["___ Auto ist neu.","Das",["Das","Der","Die"],"To auto je nové."],["___ Bücher sind interessant.","Die",["Die","Der","Das"],"Ty knihy jsou zajímavé."]]},
 {id:"de_g_pres",title:"Přítomný čas pravidelných sloves",type:"grammar",theory:"Pravidelná slovesa se v přítomném čase časují podle koncovek: -e, -st, -t, -en, -t, -en. Např. sloveso <b>spielen</b> (hrát): ich spiele, du spielst, er/sie/es spielt, wir spielen, ihr spielt, sie/Sie spielen.",table:[["Osoba","spielen"],["ich","spiele"],["du","spielst"],["er/sie/es","spielt"],["wir","spielen"],["ihr","spielt"],["sie/Sie","spielen"]],items:[["Ich ___ Fußball.","spiele",["spiele","spielst","spielt"],"Hraju fotbal."],["Du ___ deine Hausaufgaben.","machst",["machst","mache","macht"],"Děláš domácí úkoly."],["Er ___ in Berlin.","wohnt",["wohnt","wohne","wohnst"],"Bydlí v Berlíně."],["Wir ___ Deutsch.","lernen",["lernen","lernt","lernst"],"Učíme se německy."],["Ihr ___ sehr gut Klavier.","spielt",["spielt","spielen","spielst"],"Hrajete velmi dobře na klavír."],["Sie ___ jeden Tag.","lernt",["lernt","lerne","lernen"],"Učí se každý den."],["Ich ___ in München.","wohne",["wohne","wohnt","wohnst"],"Bydlím v Mnichově."],["Sie ___ im Park.","spielen",["spielen","spielt","spielst"],"Hrají v parku."]]},
 {id:"de_g_neg",title:"Zápor: nicht a kein",type:"grammar",theory:"Sloveso nebo přídavné jméno popíráme pomocí <b>nicht</b>. Podstatné jméno bez členu nebo s neurčitým členem popíráme pomocí <b>kein/keine</b>: Ich habe kein Auto. Ich bin nicht müde.",table:[["Situace","Zápor","Příklad"],["sloveso/přídavné jméno","nicht","Ich bin nicht müde."],["podstatné jméno (a/an)","kein/keine","Ich habe kein Auto."]],items:[["Ich bin ___ müde.","nicht",["nicht","kein","keine"],"Nejsem unavený."],["Er hat ___ Auto.","kein",["kein","nicht","keine"],"Nemá auto."],["Wir haben ___ Zeit.","keine",["keine","kein","nicht"],"Nemáme čas."],["Sie kommt heute ___ .","nicht",["nicht","kein","keine"],"Dnes nepřijde."],["Das ist ___ richtig.","nicht",["nicht","kein","keine"],"To není správně."],["Ich habe ___ Geschwister.","keine",["keine","kein","nicht"],"Nemám sourozence."],["Er trinkt ___ Kaffee.","keinen",["keinen","kein","nicht"],"Nepije kávu."],["Wir sind ___ fertig.","nicht",["nicht","kein","keine"],"Nejsme hotoví."]]},
 {id:"de_g_akk",title:"4. pád (Akkusativ)",type:"grammar",theory:"Čtvrtý pád (Akkusativ) se používá u přímého předmětu. Mužský člen se mění: der → den. Ženský, střední a množné číslo zůstávají stejné: die → die, das → das.",table:[["1. pád (Nominativ)","4. pád (Akkusativ)"],["der Mann","den Mann"],["die Frau","die Frau"],["das Kind","das Kind"],["die Kinder","die Kinder"]],items:[["Ich sehe ___ Mann.","den",["den","der","dem"],"Vidím toho muže."],["Er kauft ___ Auto.","das",["das","der","die"],"Kupuje to auto."],["Wir suchen ___ Lehrerin.","die",["die","der","den"],"Hledáme tu učitelku."],["Sie liebt ___ Hund.","den",["den","der","das"],"Miluje toho psa."],["Ich lese ___ Buch.","das",["das","den","die"],"Čtu tu knihu."],["Wir besuchen ___ Großmutter.","die",["die","den","das"],"Navštěvujeme babičku."],["Er trinkt ___ Kaffee.","den",["den","die","das"],"Pije tu kávu."],["Ich brauche ___ Wasser.","das",["das","den","die"],"Potřebuji tu vodu."]]},
 {id:"de_g_poss",title:"Přivlastňovací zájmena",type:"grammar",theory:"Přivlastňovací zájmena (mein, dein, sein, ihr, unser, euer, ihr/Ihr) se shodují s rodem podstatného jména podobně jako členy: mein Vater, meine Mutter, mein Kind.",table:[["Osoba","mužský/střední","ženský/množné"],["ich","mein","meine"],["du","dein","deine"],["er","sein","seine"],["sie","ihr","ihre"],["wir","unser","unsere"]],items:[["Das ist ___ Bruder.","mein",["mein","meine","meinen"],"To je můj bratr."],["Wo ist ___ Tasche?","deine",["deine","dein","deinen"],"Kde je tvoje taška?"],["Er liebt ___ Familie.","seine",["seine","sein","seinen"],"Miluje svou rodinu."],["Sie besucht ___ Großmutter.","ihre",["ihre","ihr","ihren"],"Navštěvuje svou babičku."],["___ Haus ist sehr groß.","Unser",["Unser","Unsere","Unseren"],"Náš dům je velmi velký."],["Ist das ___ Auto?","dein",["dein","deine","deinen"],"Je to tvoje auto?"],["___ Kinder spielen im Garten.","Meine",["Meine","Mein","Meinen"],"Moje děti si hrají na zahradě."],["Er trägt ___ Jacke.","seine",["seine","sein","seinen"],"Nosí svou bundu."]]},
 {id:"de_g_modal",title:"Modální slovesa",type:"grammar",theory:"Modální slovesa (können, müssen, wollen, dürfen, sollen) mění tvar podle osoby a druhé sloveso jde v infinitivu na konec věty: Ich kann gut schwimmen. Er muss jetzt gehen.",table:[["Osoba","können","müssen","wollen"],["ich","kann","muss","will"],["du","kannst","musst","willst"],["er/sie/es","kann","muss","will"],["wir","können","müssen","wollen"],["ihr","könnt","müsst","wollt"],["sie/Sie","können","müssen","wollen"]],items:[["Ich ___ gut schwimmen.","kann",["kann","kannst","können"],"Umím dobře plavat."],["Du ___ jetzt nach Hause gehen.","musst",["musst","muss","müssen"],"Musíš teď jít domů."],["Er ___ ein neues Auto kaufen.","will",["will","willst","wollen"],"Chce koupit nové auto."],["Wir ___ Deutsch lernen.","müssen",["müssen","muss","musst"],"Musíme se učit německy."],["___ ihr mir helfen?","Könnt",["Könnt","Kann","Kannst"],"Můžete mi pomoct?"],["Sie ___ heute Abend kommen.","wollen",["wollen","will","willst"],"Chtějí dnes večer přijít."],["Ich ___ leider nicht kommen.","kann",["kann","kannst","könnt"],"Bohužel nemůžu přijít."],["Man ___ hier nicht rauchen.","darf",["darf","muss","will"],"Tady se nesmí kouřit."]]},
 {id:"de_g_esgibt",title:"Es gibt (existuje/je)",type:"grammar",theory:"Vazba <b>es gibt</b> se používá k vyjádření existence něčeho, podobně jako anglické 'there is/are'. Podstatné jméno po ní je vždy ve 4. pádě (Akkusativ): Es gibt einen Park in der Stadt.",table:[["Vzorec","Příklad"],["Es gibt + Akkusativ","Es gibt einen Park."],["Es gibt kein/keine + podst. jméno","Es gibt keinen Park."]],items:[["Es ___ einen Park in der Stadt.","gibt",["gibt","gibst","geben"],"Ve městě je park."],["___ es hier ein Restaurant?","Gibt",["Gibt","Gibst","Geben"],"Je tady restaurace?"],["Es gibt ___ Milch mehr.","keine",["keine","kein","nicht"],"Už není žádné mléko."],["In diesem Haus ___ es drei Zimmer.","gibt",["gibt","gibst","geben"],"V tomto domě jsou tři pokoje."],["Es gibt heute ___ Schule.","keine",["keine","kein","nicht"],"Dnes není žádná škola."],["___ es einen Bus zum Bahnhof?","Gibt",["Gibt","Gibst","Geben"],"Jede autobus na nádraží?"],["Es gibt ___ Menschen hier.","viele",["viele","viel","vielen"],"Je tu hodně lidí."],["Es ___ leider keinen Kaffee mehr.","gibt",["gibt","gibst","geben"],"Bohužel už není žádná káva."]]},
 {id:"de_g_wfrage",title:"W-otázky a slovosled",type:"grammar",theory:"V němčině je sloveso v oznamovací větě vždy na druhém místě. W-otázky (wer, was, wo, wann, warum, wie) stojí na prvním místě, sloveso hned za nimi: Wo wohnst du? Was machst du?",table:[["Tázací zájmeno","Význam"],["wer","kdo"],["was","co"],["wo","kde"],["wann","kdy"],["warum","proč"],["wie","jak"]],items:[["___ wohnst du?","Wo",["Wo","Was","Wer"],"Kde bydlíš?"],["___ heißt du?","Wie",["Wie","Was","Wo"],"Jak se jmenuješ?"],["___ kommst du morgen?","Wann",["Wann","Wo","Wer"],"Kdy zítra přijdeš?"],["___ ist das?","Wer",["Wer","Was","Wo"],"Kdo to je?"],["___ machst du heute Abend?","Was",["Was","Wer","Wo"],"Co děláš dnes večer?"],["___ lernst du Deutsch?","Warum",["Warum","Wann","Wie"],"Proč se učíš německy?"],["___ kostet das Buch?","Wie viel",["Wie viel","Was","Wo"],"Kolik stojí ta kniha?"],["___ ist die Bibliothek?","Wo",["Wo","Wer","Was"],"Kde je knihovna?"]]}
];
const PATH_A1_DE=["de_greet","de_numbers","de_family","de_g_seinhaben","de_food","de_colors","de_animals","de_g_artikel","de_body","de_house","de_g_pres","de_clothes","de_time","de_g_neg","de_town","de_transport","de_g_akk","de_weather","de_g_poss","de_verbs","de_g_modal","de_adj","de_g_esgibt","de_g_wfrage","de_a1_test"];

window.LANG_DATA = window.LANG_DATA || {};
window.LANG_DATA.de = {levels:{
  A1:{cats:CATS_A1_DE,gram:GRAMMAR_A1_DE,path:PATH_A1_DE,test:'de_a1_test'}
}};
if(window.onLangPackLoaded)window.onLangPackLoaded('de');
})();
