/* ===== Rozhraní: Deutsch (de) =====
   Klíčem je původní český text. Chybějící klíč = zůstane česky,
   takže neúplný překlad nikdy nic nerozbije. */
window.UI_DATA = window.UI_DATA || {};
window.UI_DATA.de = {
 "Angličtina": "Englisch",
 "Němčina": "Deutsch",
 "Čeština": "Tschechisch",
 "Lvl": "Lvl",
 "Body": "Punkte",
 "dní": "Tage",
 "Změnit jazyk rozhraní": "Sprache der Oberfläche ändern",
 "Přepnout jazyk": "Sprache wechseln",
 "Účet a synchronizace": "Konto & Synchronisierung",
 "Světlý / tmavý režim": "Heller / dunkler Modus",
 "dnešní cíl": "Tagesziel",
 "Level": "Level",
 "bodů": "Punkte",
 "b do levelu · série": "P. bis zum nächsten Level · Serie",
 "Dnešní mise": "Heutige Mission",
 "Opakování": "Wiederholung",
 "Slova k zopakování (SRS)": "Fällige Wörter (SRS)",
 "Problémová slova": "Problemwörter",
 "Slova, ve kterých chybuješ": "Wörter, bei denen du Fehler machst",
 "Zamíchat vše": "Alles mischen",
 "Náhodně napříč tématy": "Zufällig aus allen Themen",
 "5 minut denně": "5 Minuten am Tag",
 "Krátká rychlá lekce": "Eine kurze schnelle Lektion",
 "Statistiky": "Statistiken",
 "Pokrok a slabá témata": "Fortschritt und schwache Themen",
 "Směr": "Richtung",
 "Doplňování": "Antworten",
 "Denní cíl": "Tagesziel",
 "Mix": "Mix",
 "Výběr": "Auswahl",
 "Psaní": "Tippen",
 "Vyber úroveň znalosti": "Wähle dein Niveau",
 "Na jaké úrovni chceš procvičovat? Každá úroveň má vlastní témata i postup.": "Auf welchem Niveau möchtest du üben? Jedes Niveau hat eigene Themen und einen eigenen Fortschritt.",
 "🎯 Nevím, jakou úroveň zvolit — udělat rozřazovací test": "🎯 Unsicher beim Niveau — Einstufungstest machen",
 "Připravujeme": "In Vorbereitung",
 "Tato úroveň zatím není k dispozici.": "Dieses Niveau ist noch nicht verfügbar.",
 "Brzy": "Bald",
 "Začít": "Starten",
 "Odemkni testem na": "Freischalten mit einem Testergebnis von",
 "teď": "jetzt",
 "Úroveň": "Niveau",
 "se odemkne po zvládnutí předchozího závěrečného testu na": "wird freigeschaltet nach dem vorherigen Abschlusstest mit",
 "Nastaveno na úroveň": "Eingestellt auf Niveau",
 "Témata": "Themen",
 "← Změnit úroveň": "← Niveau ändern",
 "Úspěchy": "Erfolge",
 "Jakým jazykem mluvíš?": "Welche Sprache sprichst du?",
 "Zvol jazyk, ve kterém ti bude appka vysvětlovat. Podle něj se nabídnou jazyky, které se můžeš učit.": "Wähle die Sprache, in der die App dir alles erklärt. Danach richten sich die Sprachen, die du lernen kannst.",
 "zvoleno": "ausgewählt",
 "Zvolit": "Auswählen",
 "Přepnuto na": "Gewechselt zu",
 "Nepodařilo se načíst jazyk – zkontroluj připojení a zkus to znovu": "Sprache konnte nicht geladen werden — prüfe deine Verbindung und versuche es erneut",
 "← Zpět": "← Zurück",
 "Závěrečný test": "Abschlusstest",
 "adaptivní učení": "adaptives Lernen",
 "Začátek": "Anfang",
 "Dokonči první lekci": "Schließe die erste Lektion ab",
 "Level 5": "Level 5",
 "Dosáhni levelu 5": "Erreiche Level 5",
 "7 dní": "7 Tage",
 "7 dní v řadě": "7 Tage in Folge",
 "50 slov": "50 Wörter",
 "Nauč se 50 slov": "Lerne 50 Wörter",
 "150 slov": "150 Wörter",
 "Nauč se 150 slov": "Lerne 150 Wörter",
 "Bez problémů": "Keine Probleme",
 "Vyčisti všechna problémová slova": "Räume alle Problemwörter ab",
 "Úspěch": "Erfolg",
 "právě teď": "gerade eben",
 "před": "vor",
 "min": "Min.",
 "včera": "gestern",
 "dny": "Tagen",
 "Denní cíl splněn! Série": "Tagesziel erreicht! Serie",
 "Nové téma odemčeno": "Neues Thema freigeschaltet",
 "Celkem": "Insgesamt",
 "slov · naučeno": "Wörter · gelernt",
 "Klikni na téma pro výběr cvičení.": "Klicke auf ein Thema, um eine Übung zu wählen.",
 "Gramatika": "Grammatik",
 "zamčeno": "gesperrt",
 "Zamčeno": "Gesperrt",
 "dokonči": "schließe ab",
 "pokračuj v cestě": "setze den Weg fort",
 "nejlepší výsledek": "bestes Ergebnis",
 "prověř všechna témata": "alle Themen prüfen",
 "k opakování": "zu wiederholen",
 "hotovo": "fertig",
 "cvičení": "Übungen",
 "naučeno": "gelernt",
 "rozpracováno": "in Arbeit",
 "slov": "Wörter",
 "Nevyzkoušeno": "Noch nicht versucht",
 "Naposledy": "Zuletzt",
 "Slovíčka": "Vokabeln",
 "Kartičky · Umím / Neumím": "Karteikarten · Kann ich / Kann ich nicht",
 "Kvíz": "Quiz",
 "Výběr překladu": "Übersetzung auswählen",
 "Doplň větu": "Satz ergänzen",
 "Výběr nebo psaní": "Auswahl oder Tippen",
 "Poslech": "Hörverstehen",
 "Přehraje se jednou": "Wird einmal abgespielt",
 "Diktát": "Diktat",
 "Poslechni a napiš": "Hören und schreiben",
 "Mluvení": "Sprechen",
 "Bonus · nehodnotí se": "Bonus · wird nicht bewertet",
 "Teorie": "Theorie",
 "Vysvětlení + příklady": "Erklärung + Beispiele",
 "Vyber správný tvar": "Wähle die richtige Form",
 "Doplň": "Ergänzen",
 "Napiš správný tvar": "Schreibe die richtige Form",
 "Přečteno": "Gelesen",
 "Nepřečteno": "Nicht gelesen",
 "Prověř všechna témata najednou": "Alle Themen auf einmal prüfen",
 "nejlepší": "bestes",
 "Spustit test": "Test starten",
 "30 otázek napříč slovíčky i gramatikou · na 60 % ho dokončíš": "30 Fragen aus Vokabeln und Grammatik · ab 60 % bestanden",
 "Nejlepší": "Bestes",
 "dokončeno": "abgeschlossen",
 "přečti teorii a zvládni kvíz na": "lies die Theorie und bestehe das Quiz mit",
 "téma dokončeno": "Thema abgeschlossen",
 "cvičení na": "Übungen mit",
 "Nejdřív dokonči předchozí témata 🔒": "Schließe zuerst die vorherigen Themen ab 🔒",
 "Hotovo": "Fertig",
 "zbývá": "übrig",
 "správně": "richtig",
 "čas": "Zeit",
 "denní cíl": "Tagesziel",
 "Domů": "Startseite",
 "Další": "Weiter",
 "Správně": "Richtig",
 "doplň": "ergänzen",
 "kvíz": "Quiz",
 "Nic k procvičení.": "Nichts zu üben.",
 "Teď není co opakovat 👌": "Gerade nichts zu wiederholen 👌",
 "Žádná problémová slova 🎉": "Keine Problemwörter 🎉",
 "Teorie přečtena · +5": "Theorie gelesen · +5",
 "Přehraje se jen jednou — poslouchej pozorně 🙂": "Wird nur einmal abgespielt — hör gut zu 🙂",
 "Přehraje se jen jednou 🙂": "Wird nur einmal abgespielt 🙂",
 "Rozřazovací test": "Einstufungstest",
 "Otázka": "Frage",
 "odhad úrovně": "geschätztes Niveau",
 "otázek": "Fragen",
 "úroveň": "Niveau",
 "Podle tvých odpovědí ti nejlíp sedí úroveň": "Nach deinen Antworten passt am besten das Niveau",
 "Nižší úrovně zůstanou odemčené, kdybys je někdy chtěl projít.": "Niedrigere Niveaus bleiben freigeschaltet, falls du sie durchgehen möchtest.",
 "Začít na úrovni": "Auf Niveau starten",
 "Příklady": "Beispiele",
 "Rozumím": "Verstanden",
 "napiš správný tvar": "schreibe die richtige Form",
 "doplň větu": "Satz ergänzen",
 "Výslovnost": "Aussprache",
 "klikni pro překlad": "für die Übersetzung klicken",
 "Neumím": "Kann ich nicht",
 "Umím": "Kann ich",
 "Vyber překlad": "Wähle die Übersetzung",
 "Poslechni a vyber slovo (přehraje se jen jednou)": "Hör zu und wähle das Wort (wird nur einmal abgespielt)",
 "napiš chybějící slovo": "schreibe das fehlende Wort",
 "Napiš překlad": "Schreibe die Übersetzung",
 "Poslechni a napiš, co jsi slyšel/a (jen jednou)": "Hör zu und schreibe, was du gehört hast (nur einmal)",
 "napiš překlad…": "schreibe die Übersetzung…",
 "Rozpoznávání řeči tvůj prohlížeč nepodporuje. Vyzkoušej Chrome nebo Edge.": "Dein Browser unterstützt keine Spracherkennung. Versuche Chrome oder Edge.",
 "Mluvení na zkoušku — řekni slovo a uvidíš, jestli ti appka rozumí.": "Sprechübung — sag das Wort und schau, ob die App dich versteht.",
 "Není to známka z výslovnosti": "Es ist keine Aussprachenote",
 "jen cvičení.": "nur eine Übung.",
 "Poslechni vzor": "Beispiel anhören",
 "Klikni na mikrofon a zkus slovo říct": "Klicke auf das Mikrofon und sprich das Wort",
 "Poslouchám…": "Ich höre zu…",
 "Super, appka ti rozuměla! Slyšela:": "Super, die App hat dich verstanden! Sie hat gehört:",
 "Můžeš zkusit znovu, nebo pokračovat dál.": "Du kannst es nochmal versuchen oder weitergehen.",
 "Nerozpoznala jsem to úplně (slyšela": "Nicht ganz erkannt (gehört wurde",
 "Nevadí — zkus to klidně znovu.": "Kein Problem — versuch es ruhig nochmal.",
 "Zkus to znovu, nebo pokračuj tlačítkem Další.": "Versuch es nochmal oder geh mit Weiter voran.",
 "Mikrofon se nepodařilo použít — můžeš pokračovat dál.": "Das Mikrofon konnte nicht verwendet werden — du kannst weitergehen.",
 "Naučená slova": "Gelernte Wörter",
 "Úspěšnost": "Trefferquote",
 "Nejlepší série": "Beste Serie",
 "Dnešní pokrok": "Heutiger Fortschritt",
 "Celkem odpovědí": "Antworten insgesamt",
 "Čas učení": "Lernzeit",
 "Tvůj celkový pokrok.": "Dein gesamter Fortschritt.",
 "Nejslabší témata": "Schwächste Themen",
 "Zatím žádná data — začni procvičovat.": "Noch keine Daten — fang an zu üben.",
 "Vymazat veškerý postup": "Gesamten Fortschritt löschen",
 "← Ukončit": "← Beenden",
 "Kdo se učí?": "Wer lernt?",
 "Vyber svůj profil nebo vytvoř nový.": "Wähle dein Profil oder erstelle ein neues.",
 "Nový profil": "Neues Profil",
 "Zadej jméno. PIN je nepovinný (4 číslice, chrání profil).": "Gib einen Namen ein. Die PIN ist optional (4 Ziffern, schützt das Profil).",
 "jméno": "Name",
 "PIN (nepovinné)": "PIN (optional)",
 "Vytvořit profil": "Profil erstellen",
 "Zadej jméno": "Gib einen Namen ein",
 "Špatný PIN": "Falsche PIN",
 "Já": "Ich",
 "Opravdu vymazat veškerý postup tohoto profilu?": "Wirklich den gesamten Fortschritt dieses Profils löschen?",
 "Postup profilu vymazán": "Profilfortschritt gelöscht",
 "Synchronizace zatím není nastavená. Do souboru je potřeba jednou vložit tvůj": "Die Synchronisierung ist noch nicht eingerichtet. Du musst einmalig deine",
 "(do části FIREBASE_CONFIG v kódu). Je to zdarma a na pár minut.": "in den Abschnitt FIREBASE_CONFIG im Code einfügen. Das ist kostenlos und dauert ein paar Minuten.",
 "Bez nastavení appka funguje normálně, jen ukládá postup lokálně na tomto počítači.": "Ohne sie funktioniert die App normal, sie speichert den Fortschritt nur lokal auf diesem Computer.",
 "Přihlášen jako": "Angemeldet als",
 "uživatel": "Benutzer",
 "Postup se ukládá do cloudu automaticky a načte se na jiném zařízení po přihlášení.": "Der Fortschritt wird automatisch in der Cloud gespeichert und nach der Anmeldung auf einem anderen Gerät geladen.",
 "Synchronizováno": "Synchronisiert",
 "Uložit teď": "Jetzt speichern",
 "Odhlásit": "Abmelden",
 "Změnit heslo": "Passwort ändern",
 "současné heslo": "aktuelles Passwort",
 "nové heslo (min. 6 znaků)": "neues Passwort (mind. 6 Zeichen)",
 "Uložit nové heslo": "Neues Passwort speichern",
 "Přihlas se, aby se tvůj postup ukládal do cloudu a byl dostupný i na druhém počítači.": "Melde dich an, damit dein Fortschritt in der Cloud gespeichert und auch auf einem anderen Computer verfügbar ist.",
 "e-mail": "E-Mail",
 "heslo (min. 6 znaků)": "Passwort (mind. 6 Zeichen)",
 "Přihlásit": "Anmelden",
 "Vytvořit účet": "Konto erstellen",
 "Zapomněl jsi heslo?": "Passwort vergessen?",
 "Zobrazit heslo": "Passwort anzeigen",
 "Skrýt heslo": "Passwort verbergen",
 "Ukládám do cloudu…": "Speichere in der Cloud…",
 "Uloženo": "Gespeichert",
 "Načteno z cloudu ✓": "Aus der Cloud geladen ✓",
 "Chyba načítání": "Ladefehler",
 "Chyba ukládání (zkontroluj pravidla Firestore)": "Speicherfehler (prüfe deine Firestore-Regeln)",
 "Přihlášeno ✓": "Angemeldet ✓",
 "Odhlášeno": "Abgemeldet",
 "Účet vytvořen ✓": "Konto erstellt ✓",
 "Heslo změněno ✓": "Passwort geändert ✓",
 "Vyplň e-mail a heslo": "Gib E-Mail und Passwort ein",
 "Zadej současné heslo": "Gib dein aktuelles Passwort ein",
 "Současné heslo je špatně": "Dein aktuelles Passwort ist falsch",
 "Nové heslo musí mít aspoň 6 znaků": "Das neue Passwort muss mindestens 6 Zeichen haben",
 "Napiš e-mail výše a klikni znovu": "Gib oben deine E-Mail ein und klicke erneut",
 "Poslali jsme e-mail pro obnovení hesla ✓": "Wir haben eine E-Mail zum Zurücksetzen des Passworts gesendet ✓",
 "špatný e-mail nebo heslo": "falsche E-Mail oder falsches Passwort",
 "účet neexistuje": "das Konto existiert nicht",
 "e-mail už je použit": "diese E-Mail wird bereits verwendet",
 "slabé heslo (min. 6 znaků)": "schwaches Passwort (mind. 6 Zeichen)",
 "neplatný e-mail": "ungültige E-Mail",
 "chyba": "Fehler",
 "Adaptivní opakování (SRS) plánuje každé slovo zvlášť: chyba → za 2 min, správně → za hodinu → den → týden → měsíc. Postup se ukládá v tomto prohlížeči.": "Adaptive Wiederholung (SRS) plant jedes Wort einzeln: falsch → in 2 Min., richtig → in einer Stunde → einem Tag → einer Woche → einem Monat. Der Fortschritt wird in diesem Browser gespeichert.",
 "Nedostupné offline (potřebují server): AI konverzace, AI generované věty, synchronizace mezi zařízeními, obrázky ke slovům.": "Offline nicht verfügbar (benötigen einen Server): KI-Konversation, KI-generierte Sätze, geräteübergreifende Synchronisierung, Bilder zu Wörtern."
};
