/* ===== Rozhraní: Deutsch (de) =====
   Klíčem je původní český text. Chybějící klíč = zůstane česky,
   takže neúplný překlad nikdy nic nerozbije. */
window.UI_DATA = window.UI_DATA || {};
window.UI_DATA.de = {
 "Angličtina": "Englisch",
 "Němčina": "Deutsch",
 "Čeština": "Tschechisch",
 "Lvl": "Lvl",
 "Body": "Punkte",
 "dní": "Tage",
 "Změnit jazyk rozhraní": "Sprache der Oberfläche ändern",
 "Přepnout jazyk": "Sprache wechseln",
 "Účet a synchronizace": "Konto & Synchronisierung",
 "Světlý / tmavý režim": "Heller / dunkler Modus",
 "dnešní cíl": "Tagesziel",
 "Level": "Level",
 "bodů": "Punkte",
 "b do levelu · série": "P. bis zum nächsten Level · Serie",
 "Dnešní mise": "Heutige Mission",
 "Opakování": "Wiederholung",
 "Slova k zopakování (SRS)": "Fällige Wörter (SRS)",
 "Problémová slova": "Problemwörter",
 "Slova, ve kterých chybuješ": "Wörter, bei denen du Fehler machst",
 "Zamíchat vše": "Alles mischen",
 "Náhodně napříč tématy": "Zufällig aus allen Themen",
 "5 minut denně": "5 Minuten am Tag",
 "Krátká rychlá lekce": "Eine kurze schnelle Lektion",
 "Statistiky": "Statistiken",
 "Pokrok a slabá témata": "Fortschritt und schwache Themen",
 "Směr": "Richtung",
 "Doplňování": "Antworten",
 "Denní cíl": "Tagesziel",
 "Mix": "Mix",
 "Výběr": "Auswahl",
 "Psaní": "Tippen",
 "Vyber úroveň znalosti": "Wähle dein Niveau",
 "Na jaké úrovni chceš procvičovat? Každá úroveň má vlastní témata i postup.": "Auf welchem Niveau möchtest du üben? Jedes Niveau hat eigene Themen und einen eigenen Fortschritt.",
 "🎯 Nevím, jakou úroveň zvolit — udělat rozřazovací test": "🎯 Unsicher beim Niveau — Einstufungstest machen",
 "Připravujeme": "In Vorbereitung",
 "Tato úroveň zatím není k dispozici.": "Dieses Niveau ist noch nicht verfügbar.",
 "Brzy": "Bald",
 "Začít": "Starten",
 "Odemkni testem na": "Freischalten mit einem Testergebnis von",
 "teď": "jetzt",
 "Úroveň": "Niveau",
 "se odemkne po zvládnutí předchozího závěrečného testu na": "wird freigeschaltet nach dem vorherigen Abschlusstest mit",
 "Nastaveno na úroveň": "Eingestellt auf Niveau",
 "Témata": "Themen",
 "← Změnit úroveň": "← Niveau ändern",
 "Úspěchy": "Erfolge",
 "Jakým jazykem mluvíš?": "Welche Sprache sprichst du?",
 "Zvol jazyk, ve kterém ti bude appka vysvětlovat. Podle něj se nabídnou jazyky, které se můžeš učit.": "Wähle die Sprache, in der die App dir alles erklärt. Danach richten sich die Sprachen, die du lernen kannst.",
 "zvoleno": "ausgewählt",
 "Zvolit": "Auswählen",
 "Přepnuto na": "Gewechselt zu",
 "Nepodařilo se načíst jazyk – zkontroluj připojení a zkus to znovu": "Sprache konnte nicht geladen werden — prüfe deine Verbindung und versuche es erneut",
 "← Zpět": "← Zurück",
 "Závěrečný test": "Abschlusstest",
 "adaptivní učení": "adaptives Lernen",
 "Začátek": "Anfang",
 "Dokonči první lekci": "Schließe die erste Lektion ab",
 "Level 5": "Level 5",
 "Dosáhni levelu 5": "Erreiche Level 5",
 "7 dní": "7 Tage",
 "7 dní v řadě": "7 Tage in Folge",
 "50 slov": "50 Wörter",
 "Nauč se 50 slov": "Lerne 50 Wörter",
 "150 slov": "150 Wörter",
 "Nauč se 150 slov": "Lerne 150 Wörter",
 "Bez problémů": "Keine Probleme",
 "Vyčisti všechna problémová slova": "Räume alle Problemwörter ab",
 "Úspěch": "Erfolg",
 "právě teď": "gerade eben",
 "před": "vor",
 "min": "Min.",
 "včera": "gestern",
 "dny": "Tagen",
 "Denní cíl splněn! Série": "Tagesziel erreicht! Serie",
 "Nové téma odemčeno": "Neues Thema freigeschaltet",
 "Celkem": "Insgesamt",
 "slov · naučeno": "Wörter · gelernt",
 "Klikni na téma pro výběr cvičení.": "Klicke auf ein Thema, um eine Übung zu wählen.",
 "Gramatika": "Grammatik",
 "zamčeno": "gesperrt",
 "Zamčeno": "Gesperrt",
 "dokonči": "schließe ab",
 "pokračuj v cestě": "setze den Weg fort",
 "nejlepší výsledek": "bestes Ergebnis",
 "prověř všechna témata": "alle Themen prüfen",
 "k opakování": "zu wiederholen",
 "hotovo": "fertig",
 "cvičení": "Übungen",
 "naučeno": "gelernt",
 "rozpracováno": "in Arbeit",
 "slov": "Wörter",
 "Nevyzkoušeno": "Noch nicht versucht",
 "Naposledy": "Zuletzt",
 "Slovíčka": "Vokabeln",
 "Kartičky · Umím / Neumím": "Karteikarten · Kann ich / Kann ich nicht",
 "Kvíz": "Quiz",
 "Výběr překladu": "Übersetzung auswählen",
 "Doplň větu": "Satz ergänzen",
 "Výběr nebo psaní": "Auswahl oder Tippen",
 "Poslech": "Hörverstehen",
 "Přehraje se jednou": "Wird einmal abgespielt",
 "Diktát": "Diktat",
 "Poslechni a napiš": "Hören und schreiben",
 "Mluvení": "Sprechen",
 "Bonus · nehodnotí se": "Bonus · wird nicht bewertet",
 "Teorie": "Theorie",
 "Vysvětlení + příklady": "Erklärung + Beispiele",
 "Vyber správný tvar": "Wähle die richtige Form",
 "Doplň": "Ergänzen",
 "Napiš správný tvar": "Schreibe die richtige Form",
 "Přečteno": "Gelesen",
 "Nepřečteno": "Nicht gelesen",
 "Prověř všechna témata najednou": "Alle Themen auf einmal prüfen",
 "nejlepší": "bestes",
 "Spustit test": "Test starten",
 "30 otázek napříč slovíčky i gramatikou · na 60 % ho dokončíš": "30 Fragen aus Vokabeln und Grammatik · ab 60 % bestanden",
 "Nejlepší": "Bestes",
 "dokončeno": "abgeschlossen",
 "přečti teorii a zvládni kvíz na": "lies die Theorie und bestehe das Quiz mit",
 "téma dokončeno": "Thema abgeschlossen",
 "cvičení na": "Übungen mit",
 "Nejdřív dokonči předchozí témata 🔒": "Schließe zuerst die vorherigen Themen ab 🔒",
 "Hotovo": "Fertig",
 "zbývá": "übrig",
 "správně": "richtig",
 "čas": "Zeit",
 "denní cíl": "Tagesziel",
 "Domů": "Startseite",
 "Další": "Weiter",
 "Správně": "Richtig",
 "doplň": "ergänzen",
 "kvíz": "Quiz",
 "Nic k procvičení.": "Nichts zu üben.",
 "Teď není co opakovat 👌": "Gerade nichts zu wiederholen 👌",
 "Žádná problémová slova 🎉": "Keine Problemwörter 🎉",
 "Teorie přečtena · +5": "Theorie gelesen · +5",
 "Přehraje se jen jednou — poslouchej pozorně 🙂": "Wird nur einmal abgespielt — hör gut zu 🙂",
 "Přehraje se jen jednou 🙂": "Wird nur einmal abgespielt 🙂",
 "Rozřazovací test": "Einstufungstest",
 "Otázka": "Frage",
 "odhad úrovně": "geschätztes Niveau",
 "otázek": "Fragen",
 "úroveň": "Niveau",
 "Podle tvých odpovědí ti nejlíp sedí úroveň": "Nach deinen Antworten passt am besten das Niveau",
 "Nižší úrovně zůstanou odemčené, kdybys je někdy chtěl projít.": "Niedrigere Niveaus bleiben freigeschaltet, falls du sie durchgehen möchtest.",
 "Začít na úrovni": "Auf Niveau starten",
 "Příklady": "Beispiele",
 "Rozumím": "Verstanden",
 "napiš správný tvar": "schreibe die richtige Form",
 "doplň větu": "Satz ergänzen",
 "Výslovnost": "Aussprache",
 "klikni pro překlad": "für die Übersetzung klicken",
 "Neumím": "Kann ich nicht",
 "Umím": "Kann ich",
 "Vyber překlad": "Wähle die Übersetzung",
 "Poslechni a vyber slovo (přehraje se jen jednou)": "Hör zu und wähle das Wort (wird nur einmal abgespielt)",
 "napiš chybějící slovo": "schreibe das fehlende Wort",
 "Napiš překlad": "Schreibe die Übersetzung",
 "Poslechni a napiš, co jsi slyšel/a (jen jednou)": "Hör zu und schreibe, was du gehört hast (nur einmal)",
 "napiš překlad…": "schreibe die Übersetzung…",
 "Rozpoznávání řeči tvůj prohlížeč nepodporuje. Vyzkoušej Chrome nebo Edge.": "Dein Browser unterstützt keine Spracherkennung. Versuche Chrome oder Edge.",
 "Mluvení na zkoušku — řekni slovo a uvidíš, jestli ti appka rozumí.": "Sprechübung — sag das Wort und schau, ob die App dich versteht.",
 "Není to známka z výslovnosti": "Es ist keine Aussprachenote",
 "jen cvičení.": "nur eine Übung.",
 "Poslechni vzor": "Beispiel anhören",
 "Klikni na mikrofon a zkus slovo říct": "Klicke auf das Mikrofon und sprich das Wort",
 "Poslouchám…": "Ich höre zu…",
 "Super, appka ti rozuměla! Slyšela:": "Super, die App hat dich verstanden! Sie hat gehört:",
 "Můžeš zkusit znovu, nebo pokračovat dál.": "Du kannst es nochmal versuchen oder weitergehen.",
 "Nerozpoznala jsem to úplně (slyšela": "Nicht ganz erkannt (gehört wurde",
 "Nevadí — zkus to klidně znovu.": "Kein Problem — versuch es ruhig nochmal.",
 "Zkus to znovu, nebo pokračuj tlačítkem Další.": "Versuch es nochmal oder geh mit Weiter voran.",
 "Mikrofon se nepodařilo použít — můžeš pokračovat dál.": "Das Mikrofon konnte nicht verwendet werden — du kannst weitergehen.",
 "Naučená slova": "Gelernte Wörter",
 "Úspěšnost": "Trefferquote",
 "Nejlepší série": "Beste Serie",
 "Dnešní pokrok": "Heutiger Fortschritt",
 "Celkem odpovědí": "Antworten insgesamt",
 "Čas učení": "Lernzeit",
 "Tvůj celkový pokrok.": "Dein gesamter Fortschritt.",
 "Nejslabší témata": "Schwächste Themen",
 "Zatím žádná data — začni procvičovat.": "Noch keine Daten — fang an zu üben.",
 "Vymazat veškerý postup": "Gesamten Fortschritt löschen",
 "← Ukončit": "← Beenden",
 "Kdo se učí?": "Wer lernt?",
 "Vyber svůj profil nebo vytvoř nový.": "Wähle dein Profil oder erstelle ein neues.",
 "Nový profil": "Neues Profil",
 "Zadej jméno. PIN je nepovinný (4 číslice, chrání profil).": "Gib einen Namen ein. Die PIN ist optional (4 Ziffern, schützt das Profil).",
 "jméno": "Name",
 "PIN (nepovinné)": "PIN (optional)",
 "Vytvořit profil": "Profil erstellen",
 "Zadej jméno": "Gib einen Namen ein",
 "Špatný PIN": "Falsche PIN",
 "Já": "Ich",
 "Opravdu vymazat veškerý postup tohoto profilu?": "Wirklich den gesamten Fortschritt dieses Profils löschen?",
 "Postup profilu vymazán": "Profilfortschritt gelöscht",
 "Synchronizace zatím není nastavená. Do souboru je potřeba jednou vložit tvůj": "Die Synchronisierung ist noch nicht eingerichtet. Du musst einmalig deine",
 "(do části FIREBASE_CONFIG v kódu). Je to zdarma a na pár minut.": "in den Abschnitt FIREBASE_CONFIG im Code einfügen. Das ist kostenlos und dauert ein paar Minuten.",
 "Bez nastavení appka funguje normálně, jen ukládá postup lokálně na tomto počítači.": "Ohne sie funktioniert die App normal, sie speichert den Fortschritt nur lokal auf diesem Computer.",
 "Přihlášen jako": "Angemeldet als",
 "uživatel": "Benutzer",
 "Postup se ukládá do cloudu automaticky a načte se na jiném zařízení po přihlášení.": "Der Fortschritt wird automatisch in der Cloud gespeichert und nach der Anmeldung auf einem anderen Gerät geladen.",
 "Synchronizováno": "Synchronisiert",
 "Uložit teď": "Jetzt speichern",
 "Odhlásit": "Abmelden",
 "Změnit heslo": "Passwort ändern",
 "současné heslo": "aktuelles Passwort",
 "nové heslo (min. 6 znaků)": "neues Passwort (mind. 6 Zeichen)",
 "Uložit nové heslo": "Neues Passwort speichern",
 "Přihlas se, aby se tvůj postup ukládal do cloudu a byl dostupný i na druhém počítači.": "Melde dich an, damit dein Fortschritt in der Cloud gespeichert und auch auf einem anderen Computer verfügbar ist.",
 "e-mail": "E-Mail",
 "heslo (min. 6 znaků)": "Passwort (mind. 6 Zeichen)",
 "Přihlásit": "Anmelden",
 "Vytvořit účet": "Konto erstellen",
 "Zapomněl jsi heslo?": "Passwort vergessen?",
 "Zobrazit heslo": "Passwort anzeigen",
 "Skrýt heslo": "Passwort verbergen",
 "Ukládám do cloudu…": "Speichere in der Cloud…",
 "Uloženo": "Gespeichert",
 "Načteno z cloudu ✓": "Aus der Cloud geladen ✓",
 "Chyba načítání": "Ladefehler",
 "Chyba ukládání (zkontroluj pravidla Firestore)": "Speicherfehler (prüfe deine Firestore-Regeln)",
 "Přihlášeno ✓": "Angemeldet ✓",
 "Odhlášeno": "Abgemeldet",
 "Účet vytvořen ✓": "Konto erstellt ✓",
 "Heslo změněno ✓": "Passwort geändert ✓",
 "Vyplň e-mail a heslo": "Gib E-Mail und Passwort ein",
 "Zadej současné heslo": "Gib dein aktuelles Passwort ein",
 "Současné heslo je špatně": "Dein aktuelles Passwort ist falsch",
 "Nové heslo musí mít aspoň 6 znaků": "Das neue Passwort muss mindestens 6 Zeichen haben",
 "Napiš e-mail výše a klikni znovu": "Gib oben deine E-Mail ein und klicke erneut",
 "Poslali jsme e-mail pro obnovení hesla ✓": "Wir haben eine E-Mail zum Zurücksetzen des Passworts gesendet ✓",
 "špatný e-mail nebo heslo": "falsche E-Mail oder falsches Passwort",
 "účet neexistuje": "das Konto existiert nicht",
 "e-mail už je použit": "diese E-Mail wird bereits verwendet",
 "slabé heslo (min. 6 znaků)": "schwaches Passwort (mind. 6 Zeichen)",
 "neplatný e-mail": "ungültige E-Mail",
 "chyba": "Fehler",
 "Adaptivní opakování (SRS) plánuje každé slovo zvlášť: chyba → za 2 min, správně → za hodinu → den → týden → měsíc. Postup se ukládá v tomto prohlížeči.": "Adaptive Wiederholung (SRS) plant jedes Wort einzeln: falsch → in 2 Min., richtig → in einer Stunde → einem Tag → einer Woche → einem Monat. Der Fortschritt wird in diesem Browser gespeichert.",
 "Nedostupné offline (potřebují server): AI konverzace, AI generované věty, synchronizace mezi zařízeními, obrázky ke slovům.": "Offline nicht verfügbar (benötigen einen Server): KI-Konversation, KI-generierte Sätze, geräteübergreifende Synchronisierung, Bilder zu Wörtern.",
 "Vysvětlení": "Erklärung",
 "Proč je to špatně?": "Warum ist das falsch?",
 "Zeptat se na to": "Dazu nachfragen",
 "Zeptat se": "Fragen",
 "Zeptej se na cokoli k tomuhle…": "Frag alles dazu…",
 "Přemýšlím": "Ich denke nach",
 "AI se teď nepodařilo zeptat": "Die KI ist gerade nicht erreichbar",
 "AI vysvětlování": "KI-Erklärungen",
 "API klíč": "API-Schlüssel",
 "Uložit klíč": "Schlüssel speichern",
 "Klíč uložen ✓": "Schlüssel gespeichert ✓",
 "Klíč smazán": "Schlüssel gelöscht",
 "Zapnuto přes vlastní server ✓": "An, über deinen eigenen Server ✓",
 "Režim proxy, ale chybí endpoint v ai.js": "Proxy-Modus, aber der Endpoint fehlt in ai.js",
 "Vlož svůj vlastní API klíč. Uloží se jen do tohoto prohlížeče, nikam se neodesílá.": "Füge deinen eigenen API-Schlüssel ein. Er wird nur in diesem Browser gespeichert und nirgendwohin gesendet.",
 "Zapnuto": "An",
 "Vypnuto": "Aus",
 "Po špatné odpovědi ti AI vysvětlí, proč je to špatně — a můžeš se doptat.": "Nach einer falschen Antwort erklärt dir die KI, warum sie falsch ist — und du kannst nachfragen.",
 "Bez klíče se AI tlačítka nezobrazí.": "Ohne Schlüssel erscheinen die KI-Schaltflächen nicht.",
 "Zatím nedostupné": "Noch nicht verfügbar",
 "Pracujeme na tom — máme to připravené, pustíme to, až doladíme detaily.": "Wir arbeiten daran — es ist fertig, wir schalten es frei, sobald die Details stimmen.",
 "Témata navíc": "Zusätzliche Themen",
 "Tematické sady nezávislé na úrovni — otevřené celé, sáhni si po tom, co zrovna potřebuješ.": "Themensets unabhängig vom Niveau — komplett freigeschaltet, greif dir, was du gerade brauchst.",
 "témat": "Themen",
 "od": "ab",
 "Bude náročnější než tvoje úroveň": "Wird schwerer als dein Niveau",
 "← Zpět na výběr": "← Zurück zur Auswahl",
 "Hlas": "Stimme",
 "Hlasy se ještě načítají, nebo je tento prohlížeč nemá k dispozici.": "Stimmen werden noch geladen oder sind in diesem Browser nicht verfügbar.",
 "Vyber si hlas, kterým ti appka bude číst slovíčka a věty.": "Wähle die Stimme, mit der die App Wörter und Sätze vorliest.",
 "Přehrát ukázku": "Beispiel abspielen",
 "Hlas uložen ✓": "Stimme gespeichert ✓",
 "Nastavení a účet": "Einstellungen & Konto",
 "Učím se anglicky každý den": "Ich lerne jeden Tag Englisch",
 "Učím se německy každý den": "Ich lerne jeden Tag Deutsch",
 "Jaký jazyk se dnes chceš učit?": "Welche Sprache möchtest du heute lernen?",
 "Postup se ti u každého jazyka ukládá zvlášť — můžeš je libovolně střídat.": "Dein Fortschritt wird für jede Sprache getrennt gespeichert — du kannst frei wechseln.",
 "Pokračovat": "Weitermachen",
 "Začít od výběru úrovně": "Mit der Niveauwahl beginnen",
 "Tvůj hlavní jazyk": "Deine Hauptsprache",
 "Změnit": "Ändern",
 "Zpět na výběr jazyka": "Zurück zur Sprachwahl",
 "Procvičovat": "Üben",
 "Úroveň dokončena": "Niveau abgeschlossen",
 "Zpět na téma": "Zurück zum Thema",
 "Výběr témat": "Themenauswahl",
 "ho dokončíš": "zum Bestehen",
 "přečti teorii a zvládni kvíz i doplňovačku na": "lies die Theorie und schaffe Quiz und Lückentext mit",
 "Level 10": "Level 10",
 "Dosáhni levelu 10": "Erreiche Level 10",
 "Level 20": "Level 20",
 "Dosáhni levelu 20": "Erreiche Level 20",
 "Level 50": "Level 50",
 "Dosáhni levelu 50": "Erreiche Level 50",
 "30 dní": "30 Tage",
 "30 dní v řadě": "30 Tage in Folge",
 "100 dní": "100 Tage",
 "100 dní v řadě": "100 Tage in Folge",
 "500 slov": "500 Wörter",
 "Nauč se 500 slov": "Lerne 500 Wörter",
 "1000 slov": "1000 Wörter",
 "Nauč se 1000 slov": "Lerne 1000 Wörter",
 "Základ hotový": "Grundlagen fertig",
 "Dokonči úrovně A1 i A2": "Schließe A1 und A2 ab",
 "Střední hotová": "Mittelstufe fertig",
 "Dokonči úrovně B1 i B2": "Schließe B1 und B2 ab",
 "5000 bodů": "5000 Punkte",
 "Nasbírej 5000 bodů": "Sammle 5000 Punkte",
 "30 otázek napříč slovíčky i gramatikou · na": "30 Fragen aus Wortschatz und Grammatik ·",
 "Příběhy ke čtení": "Geschichten zum Lesen",
 "Krátké příběhy — čti a poslouchej zároveň, pak si ověř porozumění pár otázkami.": "Kurze Geschichten — lies und höre gleichzeitig, dann prüfe dein Verständnis mit ein paar Fragen.",
 "Číst": "Lesen",
 "vět": "Sätze",
 "Přehrát celé": "Alles abspielen",
 "Zastavit": "Stopp",
 "Zobrazit překlad": "Übersetzung zeigen",
 "Skrýt překlad": "Übersetzung ausblenden",
 "Otázky na porozumění": "Verständnisfragen",
 "Zpět na příběh": "Zurück zur Geschichte",
 "Přehrávání není v tomto prohlížeči dostupné.": "Wiedergabe ist in diesem Browser nicht verfügbar.",
 "Příběh se nepodařilo načíst": "Die Geschichte konnte nicht geladen werden",
 "K tomuto příběhu nejsou otázky.": "Diese Geschichte hat keine Fragen.",
 "Přehrát znovu": "Nochmal abspielen",
 "Doplň slovo do věty": "Ergänze das fehlende Wort",
 "Začneme od začátku?": "Von vorne anfangen?",
 "Zdá se, že angličtina je pro tebe nová — a to je úplně v pořádku! Nemusíš dělat celý test. Doporučujeme začít od úrovně A1, kde tě všechno naučíme od nuly.": "Es sieht so aus, als wäre Englisch neu für dich — und das ist völlig in Ordnung! Du musst den ganzen Test nicht machen. Wir empfehlen, mit Niveau A1 zu beginnen, wo wir alles von Grund auf beibringen.",
 "Začít od úplných začátků (A1)": "Ganz von vorne beginnen (A1)",
 "Přesto pokračovat v testu": "Test trotzdem fortsetzen",
 "Rozumím — jdeme cvičit": "Verstanden — üben wir",
 "Konverzace s AI": "Konversation mit KI",
 "Piš jako v běžném rozhovoru — AI odpoví ve tvé úrovni a opraví chyby.": "Schreibe wie in einem echten Gespräch — die KI antwortet auf deinem Niveau und korrigiert Fehler.",
 "Piš a AI ti odpoví": "Schreibe, die KI antwortet",
 "procvičeno": "geübt",
 "Nejdřív zapni AI v Účtu": "Aktiviere zuerst die KI im Konto",
 "Nepodařilo se spojit s AI": "Verbindung zur KI fehlgeschlagen",
 "Napiš odpověď…": "Schreibe deine Antwort…",
 "Představ se": "Stell dich vor",
 "V kavárně": "Im Café",
 "Nakupování": "Einkaufen",
 "U lékaře": "Beim Arzt",
 "Na letišti": "Am Flughafen",
 "Pracovní pohovor": "Vorstellungsgespräch",
 "Stížnost v hotelu": "Beschwerde im Hotel",
 "Debata o technice": "Debatte über Technik",
 "Pracovní jednání": "Geschäftsbesprechung",
 "Kultura a společnost": "Kultur und Gesellschaft",
 "Argumentace": "Argumentation",
 "Volná konverzace": "Freies Gespräch"
};
