/* ===== Rozhraní: Deutsch (de) =====
   Klíčem je původní český text. Chybějící klíč = zůstane česky,
   takže neúplný překlad nikdy nic nerozbije. */
window.UI_DATA = window.UI_DATA || {};
window.UI_DATA.de = {
 "Angličtina": "Englisch",
 "Němčina": "Deutsch",
 "Čeština": "Tschechisch",
 "Lvl": "Lvl",
 "Body": "Punkte",
 "dní": "Tage",
 "Změnit jazyk rozhraní": "Sprache der Oberfläche ändern",
 "Přepnout jazyk": "Sprache wechseln",
 "Účet a synchronizace": "Konto & Synchronisierung",
 "Světlý / tmavý režim": "Heller / dunkler Modus",
 "dnešní cíl": "Tagesziel",
 "Level": "Level",
 "bodů": "Punkte",
 "b do levelu · série": "P. bis zum nächsten Level · Serie",
 "Dnešní mise": "Heutige Mission",
 "Opakování": "Wiederholung",
 "Slova k zopakování (SRS)": "Fällige Wörter (SRS)",
 "Problémová slova": "Problemwörter",
 "Slova, ve kterých chybuješ": "Wörter, bei denen du Fehler machst",
 "Zamíchat vše": "Alles mischen",
 "Náhodně napříč tématy": "Zufällig aus allen Themen",
 "5 minut denně": "5 Minuten am Tag",
 "Krátká rychlá lekce": "Eine kurze schnelle Lektion",
 "Statistiky": "Statistiken",
 "Pokrok a slabá témata": "Fortschritt und schwache Themen",
 "Směr": "Richtung",
 "Doplňování": "Antworten",
 "Denní cíl": "Tagesziel",
 "Mix": "Mix",
 "Výběr": "Auswahl",
 "Psaní": "Tippen",
 "Vyber úroveň znalosti": "Wähle dein Niveau",
 "Na jaké úrovni chceš procvičovat? Každá úroveň má vlastní témata i postup.": "Auf welchem Niveau möchtest du üben? Jedes Niveau hat eigene Themen und einen eigenen Fortschritt.",
 "🎯 Nevím, jakou úroveň zvolit — udělat rozřazovací test": "🎯 Unsicher beim Niveau — Einstufungstest machen",
 "Připravujeme": "In Vorbereitung",
 "Tato úroveň zatím není k dispozici.": "Dieses Niveau ist noch nicht verfügbar.",
 "Brzy": "Bald",
 "Začít": "Starten",
 "Odemkni testem na": "Freischalten mit einem Testergebnis von",
 "teď": "jetzt",
 "Úroveň": "Niveau",
 "se odemkne po zvládnutí předchozího závěrečného testu na": "wird freigeschaltet nach dem vorherigen Abschlusstest mit",
 "Nastaveno na úroveň": "Eingestellt auf Niveau",
 "Témata": "Themen",
 "← Změnit úroveň": "← Niveau ändern",
 "Úspěchy": "Erfolge",
 "Jakým jazykem mluvíš?": "Welche Sprache sprichst du?",
 "Zvol jazyk, ve kterém ti bude appka vysvětlovat. Podle něj se nabídnou jazyky, které se můžeš učit.": "Wähle die Sprache, in der die App dir alles erklärt. Danach richten sich die Sprachen, die du lernen kannst.",
 "zvoleno": "ausgewählt",
 "Zvolit": "Auswählen",
 "Přepnuto na": "Gewechselt zu",
 "Nepodařilo se načíst jazyk – zkontroluj připojení a zkus to znovu": "Sprache konnte nicht geladen werden — prüfe deine Verbindung und versuche es erneut",
 "← Zpět": "← Zurück"
};
