/* ===== Rozhraní: English (en) =====
   Klíčem je původní český text. Chybějící klíč = zůstane česky,
   takže neúplný překlad nikdy nic nerozbije. */
window.UI_DATA = window.UI_DATA || {};
window.UI_DATA.en = {
 "Angličtina": "English",
 "Němčina": "German",
 "Čeština": "Czech",
 "Lvl": "Lvl",
 "Body": "Points",
 "dní": "days",
 "Změnit jazyk rozhraní": "Change interface language",
 "Přepnout jazyk": "Switch language",
 "Účet a synchronizace": "Account & sync",
 "Světlý / tmavý režim": "Light / dark mode",
 "dnešní cíl": "today's goal",
 "Level": "Level",
 "bodů": "points",
 "b do levelu · série": "pts to next level · streak",
 "Dnešní mise": "Today's mission",
 "Opakování": "Review",
 "Slova k zopakování (SRS)": "Words due for review (SRS)",
 "Problémová slova": "Problem words",
 "Slova, ve kterých chybuješ": "Words you keep getting wrong",
 "Zamíchat vše": "Shuffle everything",
 "Náhodně napříč tématy": "Random across all topics",
 "5 minut denně": "5 minutes a day",
 "Krátká rychlá lekce": "A short quick lesson",
 "Statistiky": "Statistics",
 "Pokrok a slabá témata": "Progress and weak topics",
 "Směr": "Direction",
 "Doplňování": "Answering",
 "Denní cíl": "Daily goal",
 "Mix": "Mix",
 "Výběr": "Choice",
 "Psaní": "Typing",
 "Vyber úroveň znalosti": "Choose your level",
 "Na jaké úrovni chceš procvičovat? Každá úroveň má vlastní témata i postup.": "Which level do you want to practise? Each level has its own topics and progress.",
 "🎯 Nevím, jakou úroveň zvolit — udělat rozřazovací test": "🎯 Not sure which level — take the placement test",
 "Připravujeme": "Coming soon",
 "Tato úroveň zatím není k dispozici.": "This level isn't available yet.",
 "Brzy": "Soon",
 "Začít": "Start",
 "Odemkni testem na": "Unlock with a test score of",
 "teď": "now",
 "Úroveň": "Level",
 "se odemkne po zvládnutí předchozího závěrečného testu na": "unlocks after passing the previous final test with",
 "Nastaveno na úroveň": "Set to level",
 "Témata": "Topics",
 "← Změnit úroveň": "← Change level",
 "Úspěchy": "Achievements",
 "Jakým jazykem mluvíš?": "What language do you speak?",
 "Zvol jazyk, ve kterém ti bude appka vysvětlovat. Podle něj se nabídnou jazyky, které se můžeš učit.": "Choose the language the app will explain things in. It determines which languages you can learn.",
 "zvoleno": "selected",
 "Zvolit": "Select",
 "Přepnuto na": "Switched to",
 "Nepodařilo se načíst jazyk – zkontroluj připojení a zkus to znovu": "Couldn't load the language — check your connection and try again",
 "← Zpět": "← Back"
};
