/* ===== Rozhraní: English (en) =====
   Klíčem je původní český text. Chybějící klíč = zůstane česky,
   takže neúplný překlad nikdy nic nerozbije. */
window.UI_DATA = window.UI_DATA || {};
window.UI_DATA.en = {
 "Angličtina": "English",
 "Němčina": "German",
 "Čeština": "Czech",
 "Lvl": "Lvl",
 "Body": "Points",
 "dní": "days",
 "Změnit jazyk rozhraní": "Change interface language",
 "Přepnout jazyk": "Switch language",
 "Účet a synchronizace": "Account & sync",
 "Světlý / tmavý režim": "Light / dark mode",
 "dnešní cíl": "today's goal",
 "Level": "Level",
 "bodů": "points",
 "b do levelu · série": "pts to next level · streak",
 "Dnešní mise": "Today's mission",
 "Opakování": "Review",
 "Slova k zopakování (SRS)": "Words due for review (SRS)",
 "Problémová slova": "Problem words",
 "Slova, ve kterých chybuješ": "Words you keep getting wrong",
 "Zamíchat vše": "Shuffle everything",
 "Náhodně napříč tématy": "Random across all topics",
 "5 minut denně": "5 minutes a day",
 "Krátká rychlá lekce": "A short quick lesson",
 "Statistiky": "Statistics",
 "Pokrok a slabá témata": "Progress and weak topics",
 "Směr": "Direction",
 "Doplňování": "Answering",
 "Denní cíl": "Daily goal",
 "Mix": "Mix",
 "Výběr": "Choice",
 "Psaní": "Typing",
 "Vyber úroveň znalosti": "Choose your level",
 "Na jaké úrovni chceš procvičovat? Každá úroveň má vlastní témata i postup.": "Which level do you want to practise? Each level has its own topics and progress.",
 "🎯 Nevím, jakou úroveň zvolit — udělat rozřazovací test": "🎯 Not sure which level — take the placement test",
 "Připravujeme": "Coming soon",
 "Tato úroveň zatím není k dispozici.": "This level isn't available yet.",
 "Brzy": "Soon",
 "Začít": "Start",
 "Odemkni testem na": "Unlock with a test score of",
 "teď": "now",
 "Úroveň": "Level",
 "se odemkne po zvládnutí předchozího závěrečného testu na": "unlocks after passing the previous final test with",
 "Nastaveno na úroveň": "Set to level",
 "Témata": "Topics",
 "← Změnit úroveň": "← Change level",
 "Úspěchy": "Achievements",
 "Jakým jazykem mluvíš?": "What language do you speak?",
 "Zvol jazyk, ve kterém ti bude appka vysvětlovat. Podle něj se nabídnou jazyky, které se můžeš učit.": "Choose the language the app will explain things in. It determines which languages you can learn.",
 "zvoleno": "selected",
 "Zvolit": "Select",
 "Přepnuto na": "Switched to",
 "Nepodařilo se načíst jazyk – zkontroluj připojení a zkus to znovu": "Couldn't load the language — check your connection and try again",
 "← Zpět": "← Back",
 "Závěrečný test": "Final test",
 "adaptivní učení": "adaptive learning",
 "Začátek": "Start",
 "Dokonči první lekci": "Complete your first lesson",
 "Level 5": "Level 5",
 "Dosáhni levelu 5": "Reach level 5",
 "7 dní": "7 days",
 "7 dní v řadě": "7 days in a row",
 "50 slov": "50 words",
 "Nauč se 50 slov": "Learn 50 words",
 "150 slov": "150 words",
 "Nauč se 150 slov": "Learn 150 words",
 "Bez problémů": "No problems",
 "Vyčisti všechna problémová slova": "Clear all problem words",
 "Úspěch": "Achievement",
 "právě teď": "just now",
 "před": "",
 "min": "min ago",
 "včera": "yesterday",
 "dny": "days ago",
 "Denní cíl splněn! Série": "Daily goal reached! Streak",
 "Nové téma odemčeno": "New topic unlocked",
 "Celkem": "Total",
 "slov · naučeno": "words · learned",
 "Klikni na téma pro výběr cvičení.": "Click a topic to choose an exercise.",
 "Gramatika": "Grammar",
 "zamčeno": "locked",
 "Zamčeno": "Locked",
 "dokonči": "complete",
 "pokračuj v cestě": "continue along the path",
 "nejlepší výsledek": "best result",
 "prověř všechna témata": "test all topics",
 "k opakování": "to review",
 "hotovo": "done",
 "cvičení": "exercises",
 "naučeno": "learned",
 "rozpracováno": "in progress",
 "slov": "words",
 "Nevyzkoušeno": "Not tried yet",
 "Naposledy": "Last time",
 "Slovíčka": "Vocabulary",
 "Kartičky · Umím / Neumím": "Flashcards · Know / Don't know",
 "Kvíz": "Quiz",
 "Výběr překladu": "Choose the translation",
 "Doplň větu": "Fill in the sentence",
 "Výběr nebo psaní": "Choice or typing",
 "Poslech": "Listening",
 "Přehraje se jednou": "Plays once",
 "Diktát": "Dictation",
 "Poslechni a napiš": "Listen and write",
 "Mluvení": "Speaking",
 "Bonus · nehodnotí se": "Bonus · not graded",
 "Teorie": "Theory",
 "Vysvětlení + příklady": "Explanation + examples",
 "Vyber správný tvar": "Choose the correct form",
 "Doplň": "Fill in",
 "Napiš správný tvar": "Write the correct form",
 "Přečteno": "Read",
 "Nepřečteno": "Not read",
 "Prověř všechna témata najednou": "Test all topics at once",
 "nejlepší": "best",
 "Spustit test": "Start the test",
 "30 otázek napříč slovíčky i gramatikou · na 60 % ho dokončíš": "30 questions across vocabulary and grammar · 60 % to pass",
 "Nejlepší": "Best",
 "dokončeno": "completed",
 "přečti teorii a zvládni kvíz na": "read the theory and pass the quiz with",
 "téma dokončeno": "topic completed",
 "cvičení na": "exercises with",
 "Nejdřív dokonči předchozí témata 🔒": "Complete the previous topics first 🔒",
 "Hotovo": "Done",
 "zbývá": "remaining",
 "správně": "correct",
 "čas": "time",
 "denní cíl": "daily goal",
 "Domů": "Home",
 "Další": "Next",
 "Správně": "Correct",
 "doplň": "fill in",
 "kvíz": "quiz",
 "Nic k procvičení.": "Nothing to practise.",
 "Teď není co opakovat 👌": "Nothing to review right now 👌",
 "Žádná problémová slova 🎉": "No problem words 🎉",
 "Teorie přečtena · +5": "Theory read · +5",
 "Přehraje se jen jednou — poslouchej pozorně 🙂": "It plays only once — listen carefully 🙂",
 "Přehraje se jen jednou 🙂": "It plays only once 🙂",
 "Rozřazovací test": "Placement test",
 "Otázka": "Question",
 "odhad úrovně": "estimated level",
 "otázek": "questions",
 "úroveň": "level",
 "Podle tvých odpovědí ti nejlíp sedí úroveň": "Based on your answers, the best fit for you is level",
 "Nižší úrovně zůstanou odemčené, kdybys je někdy chtěl projít.": "Lower levels stay unlocked in case you ever want to go through them.",
 "Začít na úrovni": "Start at level",
 "Příklady": "Examples",
 "Rozumím": "Got it",
 "napiš správný tvar": "write the correct form",
 "doplň větu": "fill in the sentence",
 "Výslovnost": "Pronunciation",
 "klikni pro překlad": "click for the translation",
 "Neumím": "Don't know",
 "Umím": "Know it",
 "Vyber překlad": "Choose the translation",
 "Poslechni a vyber slovo (přehraje se jen jednou)": "Listen and choose the word (plays only once)",
 "napiš chybějící slovo": "write the missing word",
 "Napiš překlad": "Write the translation",
 "Poslechni a napiš, co jsi slyšel/a (jen jednou)": "Listen and write what you heard (only once)",
 "napiš překlad…": "write the translation…",
 "Rozpoznávání řeči tvůj prohlížeč nepodporuje. Vyzkoušej Chrome nebo Edge.": "Your browser doesn't support speech recognition. Try Chrome or Edge.",
 "Mluvení na zkoušku — řekni slovo a uvidíš, jestli ti appka rozumí.": "Speaking practice — say the word and see whether the app understands you.",
 "Není to známka z výslovnosti": "It isn't a pronunciation grade",
 "jen cvičení.": "just practice.",
 "Poslechni vzor": "Listen to the example",
 "Klikni na mikrofon a zkus slovo říct": "Click the microphone and try saying the word",
 "Poslouchám…": "Listening…",
 "Super, appka ti rozuměla! Slyšela:": "Nice, the app understood you! It heard:",
 "Můžeš zkusit znovu, nebo pokračovat dál.": "You can try again, or move on.",
 "Nerozpoznala jsem to úplně (slyšela": "Didn't quite catch that (heard",
 "Nevadí — zkus to klidně znovu.": "No worries — feel free to try again.",
 "Zkus to znovu, nebo pokračuj tlačítkem Další.": "Try again, or continue with Next.",
 "Mikrofon se nepodařilo použít — můžeš pokračovat dál.": "Couldn't use the microphone — you can move on.",
 "Naučená slova": "Words learned",
 "Úspěšnost": "Accuracy",
 "Nejlepší série": "Best streak",
 "Dnešní pokrok": "Today's progress",
 "Celkem odpovědí": "Total answers",
 "Čas učení": "Time studying",
 "Tvůj celkový pokrok.": "Your overall progress.",
 "Nejslabší témata": "Weakest topics",
 "Zatím žádná data — začni procvičovat.": "No data yet — start practising.",
 "Vymazat veškerý postup": "Erase all progress",
 "← Ukončit": "← Quit",
 "Kdo se učí?": "Who's learning?",
 "Vyber svůj profil nebo vytvoř nový.": "Choose your profile or create a new one.",
 "Nový profil": "New profile",
 "Zadej jméno. PIN je nepovinný (4 číslice, chrání profil).": "Enter a name. The PIN is optional (4 digits, protects the profile).",
 "jméno": "name",
 "PIN (nepovinné)": "PIN (optional)",
 "Vytvořit profil": "Create profile",
 "Zadej jméno": "Enter a name",
 "Špatný PIN": "Wrong PIN",
 "Já": "Me",
 "Opravdu vymazat veškerý postup tohoto profilu?": "Really erase all progress for this profile?",
 "Postup profilu vymazán": "Profile progress erased",
 "Synchronizace zatím není nastavená. Do souboru je potřeba jednou vložit tvůj": "Sync isn't set up yet. You need to paste your",
 "(do části FIREBASE_CONFIG v kódu). Je to zdarma a na pár minut.": "into the FIREBASE_CONFIG section in the code, just once. It's free and takes a few minutes.",
 "Bez nastavení appka funguje normálně, jen ukládá postup lokálně na tomto počítači.": "Without it the app works normally, it just stores progress locally on this computer.",
 "Přihlášen jako": "Signed in as",
 "uživatel": "user",
 "Postup se ukládá do cloudu automaticky a načte se na jiném zařízení po přihlášení.": "Progress is saved to the cloud automatically and loads on another device after signing in.",
 "Synchronizováno": "Synced",
 "Uložit teď": "Save now",
 "Odhlásit": "Sign out",
 "Změnit heslo": "Change password",
 "současné heslo": "current password",
 "nové heslo (min. 6 znaků)": "new password (min. 6 characters)",
 "Uložit nové heslo": "Save new password",
 "Přihlas se, aby se tvůj postup ukládal do cloudu a byl dostupný i na druhém počítači.": "Sign in so your progress is saved to the cloud and available on another computer too.",
 "e-mail": "email",
 "heslo (min. 6 znaků)": "password (min. 6 characters)",
 "Přihlásit": "Sign in",
 "Vytvořit účet": "Create account",
 "Zapomněl jsi heslo?": "Forgot your password?",
 "Zobrazit heslo": "Show password",
 "Skrýt heslo": "Hide password",
 "Ukládám do cloudu…": "Saving to the cloud…",
 "Uloženo": "Saved",
 "Načteno z cloudu ✓": "Loaded from the cloud ✓",
 "Chyba načítání": "Loading error",
 "Chyba ukládání (zkontroluj pravidla Firestore)": "Saving error (check your Firestore rules)",
 "Přihlášeno ✓": "Signed in ✓",
 "Odhlášeno": "Signed out",
 "Účet vytvořen ✓": "Account created ✓",
 "Heslo změněno ✓": "Password changed ✓",
 "Vyplň e-mail a heslo": "Fill in your email and password",
 "Zadej současné heslo": "Enter your current password",
 "Současné heslo je špatně": "Your current password is wrong",
 "Nové heslo musí mít aspoň 6 znaků": "The new password must be at least 6 characters",
 "Napiš e-mail výše a klikni znovu": "Enter your email above and click again",
 "Poslali jsme e-mail pro obnovení hesla ✓": "We've sent a password reset email ✓",
 "špatný e-mail nebo heslo": "wrong email or password",
 "účet neexistuje": "the account doesn't exist",
 "e-mail už je použit": "that email is already in use",
 "slabé heslo (min. 6 znaků)": "weak password (min. 6 characters)",
 "neplatný e-mail": "invalid email",
 "chyba": "error",
 "Adaptivní opakování (SRS) plánuje každé slovo zvlášť: chyba → za 2 min, správně → za hodinu → den → týden → měsíc. Postup se ukládá v tomto prohlížeči.": "Adaptive review (SRS) schedules each word separately: wrong → in 2 min, right → in an hour → a day → a week → a month. Progress is stored in this browser.",
 "Nedostupné offline (potřebují server): AI konverzace, AI generované věty, synchronizace mezi zařízeními, obrázky ke slovům.": "Unavailable offline (they need a server): AI conversation, AI-generated sentences, cross-device sync, word images.",
 "Vysvětlení": "Explanation",
 "Proč je to špatně?": "Why is this wrong?",
 "Zeptat se na to": "Ask about this",
 "Zeptat se": "Ask",
 "Zeptej se na cokoli k tomuhle…": "Ask anything about this…",
 "Přemýšlím": "Thinking",
 "AI se teď nepodařilo zeptat": "Couldn't reach the AI right now",
 "AI vysvětlování": "AI explanations",
 "API klíč": "API key",
 "Uložit klíč": "Save key",
 "Klíč uložen ✓": "Key saved ✓",
 "Klíč smazán": "Key deleted",
 "Vypnuto. Zapneš ho v souboru ai.js — nastav mode na proxy (doporučeno) nebo key.": "Off. Turn it on in ai.js — set mode to proxy (recommended) or key.",
 "Zapnuto přes vlastní server ✓": "On, via your own server ✓",
 "Režim proxy, ale chybí endpoint v ai.js": "Proxy mode, but the endpoint is missing in ai.js",
 "Vlož svůj vlastní API klíč. Uloží se jen do tohoto prohlížeče, nikam se neodesílá.": "Paste your own API key. It is stored only in this browser and sent nowhere else."
};
